project_id = "zzqynvjmgloobcnpatqd"

[functions.delete-user]
verify_jwt = false

[functions.list-users]
verify_jwt = false

[functions.toggle-user-role]
verify_jwt = false

[functions.create-user]
verify_jwt = false

[functions.close-month]
verify_jwt = false

[functions.auto-close-previous-month]
verify_jwt = false

[functions.sync-financial-cashflow]
verify_jwt = false