project_id = "zzqynvjmgloobcnpatqd"

[functions.delete-user]
verify_jwt = false

[functions.list-users]
verify_jwt = false

[functions.toggle-user-role]
verify_jwt = false

[functions.create-user]
verify_jwt = false